workflow:
  rules:
    # A merge request, run a merge request pipeline.
    # For example, a merge request pipeline can be triggered by a push to a branch with an associated open merge request.
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    # A change to a branch, but a merge request is open for that branch, do not run a branch pipeline.
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    # A change to a branch, but without any open merge requests, run a branch pipeline.
    - if: $CI_COMMIT_BRANCH

# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
include:
  - template: Code-Quality.gitlab-ci.yml
  - template: Jobs/Container-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

# Override the rules so that this job also runs for pipelines for merge requests
code_quality:
  rules:
    - if: $CODE_QUALITY_DISABLED
      when: never
    # - if: $CI_COMMIT_TAG || $CI_COMMIT_BRANCH
    - if: $CI_COMMIT_BRANCH || $CI_MERGE_REQUEST_IID

# Override the rules so that this job also runs for pipelines for merge requests,
# the needs so that it depends on the docker-build job,
# and sets the image name
container_scanning:
  needs:
    - docker-build
  rules:
    - if: $CONTAINER_SCANNING_DISABLED
      when: never
    # - if: $CI_COMMIT_BRANCH &&
    - if: ($CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_MERGE_REQUEST_IID) &&
        $CI_GITLAB_FIPS_MODE == "true" &&
        $CS_ANALYZER_IMAGE !~ /-(fips|ubi)\z/
      variables:
        CS_IMAGE_SUFFIX: -fips
    # - if: $CI_COMMIT_BRANCH
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_MERGE_REQUEST_IID
  variables:
    CS_IMAGE: ${CI_REGISTRY_IMAGE}:${CI_PIPELINE_IID}

# Override the rules so that this job also runs for pipelines for merge requests
nodejs-scan-sast:
  rules:
    - if: $SAST_DISABLED
      when: never
    - if: $SAST_EXCLUDED_ANALYZERS =~ /nodejs-scan/
      when: never
    # - if: $CI_COMMIT_BRANCH
    - if: $CI_COMMIT_BRANCH || $CI_MERGE_REQUEST_IID
      exists:
        - '**/package.json'

# Override the rules so that this job also runs for pipelines for merge requests
semgrep-sast:
  rules:
    - if: $SAST_DISABLED
      when: never
    - if: $SAST_EXCLUDED_ANALYZERS =~ /semgrep/
      when: never
    # - if: $CI_COMMIT_BRANCH
    - if: $CI_COMMIT_BRANCH || $CI_MERGE_REQUEST_IID
      exists:
        - '**/*.py'
        - '**/*.js'
        - '**/*.jsx'
        - '**/*.ts'
        - '**/*.tsx'
        - '**/*.c'
        - '**/*.go'

# Override the rules so that this job also runs for pipelines for merge requests
secret_detection:
  rules:
    - if: $SECRET_DETECTION_DISABLED
      when: never
    # - if: $CI_COMMIT_BRANCH
    - if: $CI_COMMIT_BRANCH || $CI_MERGE_REQUEST_IID

stages:
  - test
  - release
  - deploy

.node:
  before_script:
    - node --version
    - npm --version
    - npm install
  cache:
    key:
      files:
        - package.json
        - package-lock.json
    paths:
      - node_modules/
  image: node:lts

unit-test:
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
      junit:
        - junit.xml
    when: always
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  extends:
    - .node
  script:
    - npm run test:cov
  variables:
    DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_database?schema=public

e2e-test:
  extends:
    - .node
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_MERGE_REQUEST_IID
  services:
    - postgres:alpine
  script:
    - npx prisma generate
    - npx prisma migrate deploy
    - npm run test:e2e
  variables:
    APP_NAME: $CI_PROJECT_PATH
    APP_URL: http://localhost:3000
    DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
    POSTGRES_DB: test_database
    POSTGRES_PASSWORD: postgres
    POSTGRES_USER: postgres

.docker:
  before_script:
    - docker version
    - docker compose version
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: /certs

docker-build:
  extends:
    - .docker
  rules:
    - exists:
        - Dockerfile
      if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_MERGE_REQUEST_IID
  script:
    - PACKAGE_VERSION=$(grep '"version":' package.json | cut -d \" -f 4)
    - docker build
      --build-arg "BUILD_VERSION=$PACKAGE_VERSION"
      --build-arg "COMMIT_SHA=$CI_COMMIT_SHA"
      --build-arg "COMMIT_TIME=$CI_COMMIT_TIMESTAMP"
      --build-arg "GIT_BRANCH=$CI_COMMIT_BRANCH"
      --build-arg "PIPELINE_ID=$CI_PIPELINE_ID"
      --build-arg "PIPELINE_INTERNAL_ID=$CI_PIPELINE_IID"
      --build-arg "PIPELINE_URL=$CI_PIPELINE_URL"
      --file ./Dockerfile
      --tag "${APP_IMAGE_NAME}:latest"
      --tag "${CI_REGISTRY_IMAGE}:${CI_PIPELINE_IID}"
      .
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        docker tag "${APP_IMAGE_NAME}:latest" "${CI_REGISTRY_IMAGE}:latest"
      fi
    - docker image ls
    - docker inspect "${APP_IMAGE_NAME}:latest"
    - echo "$CI_REGISTRY_PASSWORD" | docker login --username "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - docker push --all-tags "$CI_REGISTRY_IMAGE"
  variables:
    APP_IMAGE_NAME: $CI_PROJECT_PATH

release:
  artifacts:
    paths:
      - dist/
  extends:
    - .node
  resource_group: release
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - npm run build
    - npx semantic-release
  stage: release

.deployment:
  before_script:
    - python --version
    - python -m venv ~/venv
    - source ~/venv/bin/activate
    - python -m pip install --upgrade pip setuptools wheel
    - pip --version
    - pip install awsebcli
    - eb --version
  image: python:latest
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - eb init "$CI_PROJECT_NAME" --platform node.js --region "$AWS_REGION"
    - PACKAGE_VERSION=$(grep '"version":' package.json | cut -d \" -f 4)
    # - envsubst < .ebextensions/env.yml > .ebextensions/env.config
    - sed
      --expression 's|${PACKAGE_VERSION}|'"$PACKAGE_VERSION"'|g'
      --expression 's|${CI_PIPELINE_ID}|'"$CI_PIPELINE_ID"'|g'
      --expression 's|${CI_PIPELINE_IID}|'"$CI_PIPELINE_IID"'|g'
      --expression 's|${CI_PIPELINE_URL}|'"$CI_PIPELINE_URL"'|g'
      --expression 's|${CI_COMMIT_BRANCH}|'"$CI_COMMIT_BRANCH"'|g'
      --expression 's|${CI_COMMIT_SHA}|'"$CI_COMMIT_SHA"'|g'
      --expression 's|${CI_COMMIT_TIMESTAMP}|'"'$CI_COMMIT_TIMESTAMP'"'|g'
      .ebextensions/env.yml > .ebextensions/env.config
    - eb deploy --timeout 15 "$ENVIRONMENT_NAME"
  stage: deploy

# TODO remove the dot to make the job visible
# Deploys to a staging environment
.deploy-to-staging:
  extends: .deployment
  needs:
    - release
  resource_group: deploy-staging
  variables:
    # TODO replace with proper region
    AWS_REGION: <e.g., ap-southeast-1>
    # TODO replace with proper environment name
    ENVIRONMENT_NAME: <e.g., env-name >

# TODO remove the dot to make the job visible
# Deploys to a production environment
.deploy-to-production:
  extends: .deployment
  needs:
    - release
    - deploy-to-staging
  resource_group: deploy-production
  variables:
    # TODO replace with proper region
    AWS_REGION: <e.g., ap-southeast-1>
    # TODO replace with proper environment name
    ENVIRONMENT_NAME: <e.g., env-name>
